openapi: 3.0.2
info:
  title: BMC Bandwidth Monitoring API
  description: BMC Internal Bandwidth Monitoring API
  version: '0.2'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: PhoenixNAP Team
    email: support@phoenixnap.com
    url: https://phoenixnap.com/
servers:
  - url: https://api.phoenixnap.com/bw-monitor/v1
security:
  - OAuth2:
      - internal.bmc.admin
      - internal.bmc.admin.read
tags:
  - name: VLAN Counters
    description: VLAN Counter operations
  - name: Historical VLAN Counters
    description: Historical VLAN Counter operations
paths:
  /internal/vlan-counters:
    delete:
      tags:
        - VLAN Counters
      description: Deletes the vlan counter with the provided details.
      summary: Delete VLAN counter
      operationId: deleteVlanCounter
      security:
        - OAuth2:
            - internal.bmc.admin
      parameters:
        - $ref: '#/components/parameters/vlanId'
        - $ref: '#/components/parameters/torAddresses'
        - $ref: '#/components/parameters/status'
      responses:
        '204':
          description: Deleted
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/InternalServerError'
    get:
      tags:
        - VLAN Counters
      description: Gets a list of vlan counters according to the filters specified
      summary: Retrieve list of VLAN counters
      operationId: getVlanCounters
      security:
        - OAuth2:
            - internal.bmc.admin.read
      parameters:
        - name: vlanId
          in: query
          description: Id of the VLAN. This ID have to be in the range [100, 200]
          required: false
          schema:
            type: integer
          example: 100
        - name: torAddress
          in: query
          description: Address of the TOR related to the VLAN.
          required: false
          schema:
            type: string
          example: ar1.bmc.141.11.10.phx0.cwie.net
        - name: accountId
          in: query
          description: BMC Account ID of the vlan counter.
          required: false
          schema:
            type: string
          example: 5edf1c9b4212930ac543d721
        - name: ubsClientId
          in: query
          description: Ubersmith Client Id.
          required: false
          schema:
            type: string
          example: '27283'
        - name: status
          in: query
          description: Reason for deleting a Vlan counter.
          required: false
          schema:
            type: string
            enum:
              - ARCHIVED
              - ACTIVE
              - ERROR
              - TOR_RESET
              - DELETED
        - name: yearMonth
          in: query
          description: Year month field for the vlan counter in yyyy-mm format.
          required: false
          schema:
            type: string
          example: 2020-06
      responses:
        '200':
          description: List of all vlan counters that match the filter criteria.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VlanCounter'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /internal/vlan-counters/{vlanCounterId}:
    parameters:
      - in: path
        name: vlanCounterId
        required: true
        schema:
          type: string
        description: The ID of the vlanCounter.
        example: e6afba51-7de8-4080-83ab-0f915570659c
    get:
      tags:
        - VLAN Counters
      description: Get vlan counter per id.
      summary: Retrieve VLAN counter
      operationId: getVlanCounter
      security:
        - OAuth2:
            - internal.bmc.admin.read
      responses:
        '200':
          description: Specific vlan counter details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VlanCounter'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
    patch:
      tags:
        - VLAN Counters
      description: Update status for vlan counter.
      summary: Update VLAN counter status
      operationId: updateVlanCounterStatus
      security:
        - OAuth2:
            - internal.bmc.admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VlanCounterPatchRequest'
            example:
              status: ACTIVE
      responses:
        '200':
          description: Vlan counter status updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VlanCounter'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /internal/vlan-counters-historical:
    get:
      tags:
        - Historical VLAN Counters
      description: gets a list of vlan counter historicals according to the filters specified
      summary: Retrieve historical VLAN counters
      operationId: getVlanCountersHistorical
      security:
        - OAuth2:
            - internal.bmc.admin.read
      parameters:
        - name: vlanId
          in: query
          description: Id of the VLAN. This ID have to be in the range [100, 200]
          required: false
          schema:
            type: integer
          example: 100
        - name: torAddress
          in: query
          description: Address of the TOR related to the VLAN.
          required: false
          schema:
            type: string
          example: ar1.bmc.141.11.10.phx0.cwie.net
        - name: accountId
          in: query
          description: BMC Account ID of the vlan counter historical.
          required: false
          schema:
            type: string
          example: 5edf1c9b4212930ac543d721
        - name: ubsClientId
          in: query
          description: Ubersmith Client Id.
          required: false
          schema:
            type: string
          example: '27283'
        - name: status
          in: query
          description: Reason for deleting a Vlan counter.
          required: false
          schema:
            type: string
            enum:
              - ARCHIVED
              - ERROR
              - DELETED
        - name: yearMonth
          in: query
          description: Year month field for the vlan counter in yyyy-mm format.
          required: false
          schema:
            type: string
          example: 2020-06
      responses:
        '200':
          description: List of all vlan counter historicals that match the filter criteria.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VlanCounterHistorical'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /internal/vlan-counters-historical/{vlanCounterHistoricalId}:
    parameters:
      - in: path
        name: vlanCounterHistoricalId
        required: true
        schema:
          type: string
        description: The ID of the vlanCounter historical.
        example: e6afba51-7de8-4080-83ab-0f915570659c
    get:
      tags:
        - Historical VLAN Counters
      description: Get vlan counter historical by id.
      summary: Retrieve historical VLAN counter
      operationId: getVlanCounterHistorical
      security:
        - OAuth2:
            - internal.bmc.admin.read
      responses:
        '200':
          description: Specific vlan counter historical details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VlanCounterHistorical'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://auth.phoenixnap.com/auth/realms/internal/protocol/openid-connect/token
          scopes:
            internal.bmc.admin: Grants admin access to Bandwidth Monitoring API.
            internal.bmc.admin.read: Grants read only admin access to Bandwidth Monitoring API.
  schemas:
    VlanCounter:
      type: object
      description: VlanCounter.
      properties:
        id:
          description: The unique identifier of the vlanCounter.
          type: string
          example: 5ee8e2101d08e7344fe64332
        accountId:
          description: BMC Account ID of the vlan counter.
          type: string
          example: 5edf1c9b4212930ac543d721
        ubsClientId:
          description: Ubersmith client Id owning the vlan.
          type: string
          example: '27283'
        vlanId:
          description: vlan id.
          type: integer
          format: int32
          example: 100
        torAddress:
          description: The hostname of the TOR.
          type: string
          example: ar1.bmc.141.11.10.phx0.cwie.net
        status:
          description: The status of the vlan counter.
          type: string
          enum:
            - ARCHIVED
            - ACTIVE
            - ERROR
            - TOR_RESET
            - DELETED
            - MISSING_ON_TOR
        location:
          description: The location of the TOR.
          type: string
          example: PHX
        creationDateTime:
          description: The creation time (UTC) of the vlanCounter.
          type: string
          format: date-time
          example: '2020-03-19T16:39:00Z'
        fetchedDateTime:
          description: The time (UTC) of the last read from Arista.
          type: string
          format: date-time
          example: '2020-03-19T16:39:00Z'
        currentYearMonth:
          description: The current month in relation to this counter.
          type: string
          example: 2020-06
        currentInBytes:
          description: The total number of upload bytes since the vlan was created.
          type: integer
          format: int64
          example: 1433
        currentOutBytes:
          description: The total number of download bytes since the vlan was created.
          type: integer
          format: int64
          example: 1433
        monthlyStartInBytes:
          description: The number of upload bytes at the start of the current month.
          type: integer
          format: int64
          example: 1433
        monthlyStartOutBytes:
          description: The number of download bytes at the start of the current month.
          type: integer
          format: int64
          example: 1433
        monthlyConsumedInBytes:
          description: The number of upload bytes consumed since the start of the current month.
          type: integer
          format: int64
          example: 1433
        monthlyConsumedOutBytes:
          description: The number of download bytes consumed since the start of the current month.
          type: integer
          format: int64
          example: 1433
    VlanCounterHistorical:
      type: object
      description: VlanCounter.
      properties:
        id:
          description: The unique identifier of the vlanCounter.
          type: string
          example: 5ee8e2101d08e7344fe64332
        accountId:
          description: BMC Account ID of the vlan counter.
          type: string
          example: 5edf1c9b4212930ac543d721
        ubsClientId:
          description: Ubersmith client Id owning the vlan.
          type: string
          example: '27283'
        vlanId:
          description: vlan id.
          type: integer
          format: int32
          example: 100
        torAddress:
          description: The hostname of the TOR.
          type: string
          example: ar1.bmc.141.11.10.phx0.cwie.net
        status:
          description: The status of the vlan counter.
          type: string
          enum:
            - ARCHIVED
            - ACTIVE
            - ERROR
            - TOR_RESET
            - DELETED
            - MISSING_ON_TOR
        location:
          description: The location of the TOR.
          type: string
          example: PHX
        creationDateTime:
          description: The creation time (UTC) of the vlanCounter.
          type: string
          format: date-time
          example: '2020-03-19T16:39:00Z'
        archivedDateTime:
          description: The time (UTC) when the vlan counter was archived.
          type: string
          format: date-time
          example: '2020-03-19T16:39:00Z'
        currentYearMonth:
          description: The current month in relation to this counter.
          type: string
          example: 2020-06
        currentInBytes:
          description: The total number of upload bytes since the vlan was created.
          type: integer
          format: int64
          example: 1433
        currentOutBytes:
          description: The total number of download bytes since the vlan was created.
          type: integer
          format: int64
          example: 1433
        monthlyStartInBytes:
          description: The number of upload bytes at the start of the current month.
          type: integer
          format: int64
          example: 1433
        monthlyStartOutBytes:
          description: The number of download bytes at the start of the current month.
          type: integer
          format: int64
          example: 1433
        monthlyConsumedInBytes:
          description: The number of upload bytes consumed since the start of the current month.
          type: integer
          format: int64
          example: 1433
        monthlyConsumedOutBytes:
          description: The number of download bytes consumed since the start of the current month.
          type: integer
          format: int64
          example: 1433
    VlanCounterPatchRequest:
      type: object
      description: VlanCounter patch request object.
      properties:
        status:
          description: New status to set to the vlan counter.
          type: string
          enum:
            - ARCHIVED
            - ACTIVE
            - ERROR
            - TOR_RESET
            - DELETED
      required:
        - status
    Error:
      type: object
      properties:
        message:
          type: string
          description: The description detailing the cause of the error code.
        validationErrors:
          type: array
          items:
            type: string
          readOnly: true
          description: The validation errors, if any.
      required:
        - message
  responses:
    NotFound:
      description: The server could not find the requested resource.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalServerError:
      description: The server encountered an unexpected condition that prevented it from fulfilling the request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: The given credentials are not authorized to access this endpoint.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: The request failed since this resource cannot be accessed by the provided credentials.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    BadRequest:
      description: The request failed due to invalid data provided.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    UnprocessableEntity:
      description: The request failed due to invalid semantics in the data provided.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  parameters:
    vlanId:
      name: vlanId
      in: query
      description: Id of the VLAN. This ID have to be in the range [100, 200]
      required: true
      schema:
        type: integer
      example: 100
    torAddresses:
      name: torAddresses
      in: query
      description: List of addresses of the TOR related to the VLAN.
      required: true
      schema:
        type: array
        items:
          type: string
      example: '[ "ar1.bmc.141.11.10.phx0.cwie.net", "ar1.bmc.140.11.11.phx0.cwie.net" ]'
    status:
      name: status
      in: query
      description: Reason for deleting a Vlan counter.
      required: true
      schema:
        type: string
        enum:
          - DELETED
          - ERROR